### ISSUE TITLE
Fix Pelias Geocoding issues for flights

### ISSUE THREAD

**Issue by veitu** [pledge4future/co2calculator#101]
Pelias does not find airports for some IATA codes. Instead, it finds some places that are not airports. For example, for the IATA code "HAM" (Hamburg) it finds "Hampton Inn Raleigh Durham Airport, Morrisville, NC, USA" and a couple of other places.

Also, the calculated emissions for some of the flights are ridiculously high, I am also assuming a geocoding error there. This concerns for example the flights MUC-BRE and MUC-LHR.

**Comment by han16nah** [comment]
I guess we have to find alternatives for using Pelias.
Some suggestions below:

**Free** - first choice
- [OurAirports](https://ourairports.com/data/), see also GitHub repo https://github.com/davidmegginson/ourairports-data
  - updated daily!
  - airports.csv is 10 MB
  - also on datahub.io: https://datahub.io/core/airport-codes#data-cli
  - very promising!!
- [open flights](https://openflights.org/data.html), see also GitHub repo https://github.com/jpatokal/openflights
  - I think I suggested this somewhere before or tried it out. One issue is, that is has not been maintained since 2017 I thin

**Commercial** - would not opt for these 
- [aviation edge](https://aviation-edge.com/aviation-database/) -> one-time purchase of database or use API (with limitations for free or use subscription)
- [air-port-codes](https://www.air-port-codes.com/plans-and-pricing/) - not free
- [airlabs](https://airlabs.co/iata-codes-database-api) - not free
