### ISSUE TITLE
Add average conversion factors to `emission_factors.csv` 

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/co2calculator#106]
The file `emission_factors.csv` contains the conversion factors for transportation modes. When the user doesn't specify all options (e.g. fuel_type, size) then several results are found. In this case, we need to decide which one should be taken. In cases, where there is an average values this one will be take, but not all entries contain an average value. 

Is it possible to add additional entries to the dataset with average values? Sometimes there is NaN given, but instead of assuming that these are average values it would be better if some takes a look at it and manually adds entries to the dataset which represent average values. 

In the source column we could write `UBA-adapted` for example to make clear that these entries have been added by us.

**Comment by veitu** [comment]
Buses: If the user puts in CNG or natural gas as fuel type, but does not provide the distance range, the code would now assume "long distance".
- Should long distance emission factors be added for buses with these fuel types, should the code be changed so that cng and natural gas is automatically set to "short distance", or should we remove the options cng or natural gas altogether?

For local buses, we have the size classes small, medium, large, and average; for long-distance buses we only have the size classes medium, large, and "average". 
- Should we add size class "small" for long-distance buses?

If occupancy is not provided, it is automatically set to "50".
- For fuel types cng and natural gas, only occupancy "20" is possible. Should emission factor for occupancy 50 be added?

Train: For diesel/electric long distance/short distance, there are jeweils 2 different emission factors. We have to decide which one to keep.

**Comment by han16nah** [comment]
> Buses: If the user puts in CNG or natural gas as fuel type, but does not provide the distance range, the code would now assume "long distance".
> 
>     * Should long distance emission factors be added for buses with these fuel types, should the code be changed so that cng and natural gas is automatically set to "short distance", or should we remove the options cng or natural gas altogether?
> 
> 
> For local buses, we have the size classes small, medium, large, and average; for long-distance buses we only have the size classes medium, large, and "average".
> 
>     * Should we add size class "small" for long-distance buses?
> 
> 
> If occupancy is not provided, it is automatically set to "50".
> 
>     * For fuel types cng and natural gas, only occupancy "20" is possible. Should emission factor for occupancy 50 be added?
> 
> 
> Train: For diesel/electric long distance/short distance, there are jeweils 2 different emission factors. We have to decide which one to keep.

- The question is also whether we have the respective emission factors? I guess they are missing, because we did not find them in Probas? If you find respective emission factors, feel free to add them!
- Yes, we also have tram twice in there: https://github.com/pledge4future/co2calculator/issues/105
- Do we have criteria which help us to decide which one to use? E.g., a preferred data source which is compatible with the others OR higher completeness or precision of the emission factors OR most recent data OR the one with the higher emission factors OR sth else?
