### ISSUE TITLE
Include weather in co2 emission calculation

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/co2calculator#30]

**Comment by han16nah** [comment]
There is also this [table provided by the IWU](https://www.iwu.de/publikationen/fachinformationen/energiebilanzen/).

This is what the [Greenpeace/ifeu school co2 calculator](https://co2-schulrechner.greenpeace.de/erklaerungen) uses (see "Abfrage: Ist der Wärmeenergieverbrauch bereits witterungsbereinigt?")

Maybe we can save some effort by directly using this tool or at least adapting their processing steps. @veitu Let's dicsuss this soon and address this issue again :)

**Comment by alexbercik** [comment]
Updates so far after working with @sarahmadeleine  and @veitu :

1. a function "normalize_heating" has been added to calculate.py that calls from the new file degree_days.py. 
2. We have decided to use only the integration approach as this is the highest fidelity and is (somewhat surprisingly) actually faster than the UK Met functions, for example
3. the normalization function needs to be changed. Dividing by degree days is not consistent (ex. what if degree days = 0?). We should have some reference value? 
4. A few more TODOs remain. These can all be found at the top of degree_days.py. I summarize them here:

a) check that we correctly load the API Key for openrouteservice
b) specify time bounds in get_temp_series (now pulls entire data set for given location)
c) look first at a lookup table first rather than call openrouteservice every time
d) add option for location to be given directly in latitude and longitude
e) currently pulls temperature data from data set "temp_data.nc", need to generalize, or store entire data set somewhere we can access
